import Capacitor
import UIKit

/// Registers the plugins that live in the App target rather than in an npm
/// package.
///
/// WHY THIS FILE EXISTS — it is load-bearing, and its absence is silent.
///
/// Capacitor does NOT discover plugins by scanning the Objective-C runtime.
/// `CapacitorBridge.registerPlugins()` registers the built-ins plus exactly the
/// classes named in `capacitor.config.json` → `packageClassList`, and that list
/// is generated by `npx cap sync` from the installed npm plugins. A plugin
/// written directly in this target is never in it.
///
/// So `StoreKitPlugin` and `WidgetBridgePlugin` compiled into the binary and
/// were then never registered: every call from JS rejected with `UNIMPLEMENTED`,
/// which the web layer correctly reports as "purchases aren't available in this
/// app version". That is the whole reason in-app purchase never worked in
/// production — `/api/iap/verify` was not called once, and no customer ever
/// completed a purchase.
///
/// A previous fix (283a974) added these files to the Sources build phase, which
/// was necessary but not sufficient: compiled is not registered.
///
/// If you add another plugin class to this target, register it here too.
/// Nothing will warn you — a missing registration looks exactly like a plugin
/// that was never written.
/// `@objc(MainViewController)` is deliberate and load-bearing.
///
/// A Swift subclass of an `@objc` class is registered with the Objective-C
/// runtime under its MANGLED name — `_TtC3App18MainViewController` — and
/// Interface Builder reconstructs that from `customModule`. If the two ever
/// disagree, or the file is missing from the built target, the storyboard
/// cannot instantiate the root view controller and the app launches to a black
/// screen with only `Unknown class _TtC3App18MainViewController in Interface
/// Builder file.` in the log.
///
/// An explicit `@objc` name removes the mangling from the equation: the class
/// registers as literally `MainViewController`, and `Main.storyboard` refers to
/// it by that name with **no** `customModule`. Do not re-add `customModule` —
/// it would send Interface Builder looking for the mangled name again.
@objc(MainViewController)
class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginInstance(StoreKitPlugin())
        bridge?.registerPluginInstance(WidgetBridgePlugin())
    }
}
