#!/bin/sh
# Xcode Cloud: prepare the web app before xcodebuild runs.
#
# WHY THIS IS REQUIRED, not an optimisation.
#
# The iOS project is a Capacitor wrapper. Two things it needs are GENERATED by
# `cap sync` and are deliberately not committed:
#
#   App/App/public/               the built web app (webDir), gitignored via `dist`
#   App/App/capacitor.config.json server.url, allowNavigation, packageClassList
#
# A fresh Xcode Cloud clone has neither. Without this script the archive would
# ship with no `packageClassList` — so BackgroundGeolocation, Haptics and
# PushNotifications never register — and no `server.url`, so the WebView would
# not load the live site at all. That is the exact class of failure that made
# in-app purchase silently impossible for two months: a plugin present in the
# source and absent from the binary.
#
# Runs from ci_scripts/, which Xcode Cloud places beside the .xcodeproj.
set -eu

echo "--- ci_post_clone: preparing the web build"
cd "$CI_PRIMARY_REPOSITORY_PATH"

# Node 22, NOT the 20 in .nvmrc.
#
# Those two numbers are allowed to differ and it is worth knowing why. `.nvmrc`
# tracks the SERVER runtime — the API ships on node:20-bookworm-slim — and the
# GitHub Actions workflow reads it for the test job. The iOS build has a
# different constraint: the Capacitor CLI 8 declares `engines.node >= 22.0.0`
# and refuses to run below it, so `cap sync` dies with
#
#   [fatal] The Capacitor CLI requires NodeJS >=22.0.0
#
# AFTER the whole web build has succeeded — which reads like a web problem and
# is not. This is invisible locally, where the developer machine happens to run
# a newer Node than .nvmrc claims.
NEED_NODE=22
have_node=0
if command -v node >/dev/null 2>&1; then
  major="$(node -p 'process.versions.node.split(".")[0]')"
  [ "$major" -ge "$NEED_NODE" ] && have_node=1
fi
if [ "$have_node" -eq 0 ]; then
  echo "--- installing Node ${NEED_NODE}"
  brew install node@${NEED_NODE}
  export PATH="$(brew --prefix)/opt/node@${NEED_NODE}/bin:$PATH"
fi
echo "node $(node -v)"

# pnpm comes from the packageManager field in package.json, so the version is
# pinned by the repo rather than by whatever the image happens to have.
corepack enable
corepack prepare --activate
echo "pnpm $(pnpm -v)"

pnpm install --frozen-lockfile

# `cap:build` is the same command used locally to produce a device build:
#   shared build -> tsc --noEmit -> vite build (VITE_API_URL) -> cap sync ios
# Using it rather than open-coding the steps means CI cannot drift from what a
# developer runs by hand.
pnpm --filter @mototracker/web cap:build

# Fail loudly here rather than shipping a broken archive. Both of these are the
# generated artefacts described above; if either is missing, xcodebuild would
# still succeed and produce an app that cannot work.
cfg="apps/web/ios/App/App/capacitor.config.json"
[ -s "$cfg" ] || { echo "FATAL: $cfg was not generated"; exit 1; }
grep -q '"packageClassList"' "$cfg" || { echo "FATAL: $cfg has no packageClassList"; exit 1; }
[ -f "apps/web/ios/App/App/public/index.html" ] || { echo "FATAL: web assets missing"; exit 1; }

echo "--- ci_post_clone: ok"
